{
 "title": "Channel Fees",
 "tags": [ "lightning-network" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "peer",
    "label": "Peers",
    "query": {
     "query": "label_values(lnd_channels_remote_fee_rate,peer_alias)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Median Remote Fee Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, lnd_channels_remote_fee_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Remote Base Fee",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, lnd_channels_remote_base_fee_msat)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Local Fee Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, lnd_channels_local_fee_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Local Base Fee",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, lnd_channels_local_base_fee_msat)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Local Fees", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Base Fee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "targets": [
    {
     "expr": "sum by (peer_alias) (lnd_channels_local_base_fee_msat > 0)",
     "legendFormat": "{{peer_alias}}"
    }
   ]
  },
  {
   "title": "Fee PPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "sum by (peer_alias) (lnd_channels_local_fee_rate > 0)",
     "legendFormat": "{{peer_alias}}"
    }
   ]
  },
  { "title": "Remote Fees", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Remote Base Fee",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "targets": [
    {
     "expr": "sum by (peer_alias) (lnd_channels_remote_base_fee_msat)",
     "legendFormat": "{{peer_alias}}"
    }
   ]
  },
  {
   "title": "Remote Fee PPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "sum by (peer_alias) (lnd_channels_remote_fee_rate > 0)",
     "legendFormat": "{{peer_alias}}"
    }
   ]
  },
  { "title": "Peer $peer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "peer" },
  {
   "title": "Remote Fee PPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "sum by (peer_alias) (lnd_channels_remote_fee_rate{peer_alias=\"$peer\"} > 0)",
     "legendFormat": "{{peer_alias}}"
    }
   ]
  },
  {
   "title": "Local Fee PPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "msat" } },
   "targets": [
    {
     "expr": "sum by (peer_alias) (lnd_channels_local_fee_rate{peer_alias=\"$peer\"})",
     "legendFormat": "{{peer_alias}}"
    }
   ]
  }
 ]
}